Repository healtheloper/airbnb, pull requests merged in 2022-06, with the labels that each got.

#49 [Muffin] 차트 그리는 부분 전반적인 수정
  src/components/Chart/Graph.tsx
  src/components/Chart/index.tsx
Labels: feat, sub

#50 [Park] Refactoring header layout
  src/App.tsx
  src/common/keyframes.tsx
  src/components/Background.tsx
  src/components/Calendar/MonthCards/MonthCard/index.jsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/BigMenus.tsx
  src/components/Header/BigSearchBar/Modal/index.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Header/Category.tsx
  src/components/Header/MiniSearchBar/index.tsx
  src/components/Header/UserInfo.tsx
  src/components/Header/index.tsx
  src/constants/widths.ts
Labels: feat, main, sub

#51 [Muffin] x버튼 활성화 비활성화, x버튼 클릭시 차트 값 초기화 작업
  src/components/Chart/Graph.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/contexts/PriceProvider.tsx
Labels: bug, feat

#52 [Park] Person modal 작업중
  src/common/theme.tsx
  src/components/Header/BigSearchBar/Modal/index.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Persons/index.tsx
  src/contexts/PersonProvider.tsx
Labels: feat, main

#55 [Park] apply published calendar
  package-lock.json
  package.json
  src/components/Calendar/MonthCards/MonthCard/CardBody/ClickableDate.jsx
  src/components/Calendar/MonthCards/MonthCard/CardBody/index.jsx
  src/components/Calendar/MonthCards/MonthCard/CardTitle.jsx
  src/components/Calendar/MonthCards/MonthCard/index.jsx
  src/components/Calendar/MonthCards/index.jsx
  src/components/Calendar/MonthNav/LeftArrow.jsx
  src/components/Calendar/MonthNav/RightArrow.jsx
  src/components/Calendar/MonthNav/index.jsx
  src/components/Calendar/index.jsx
  src/components/Calendar/useCalendar.jsx
  src/components/Chart/index.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/BigMenus.tsx
  src/components/Header/BigSearchBar/Modal/index.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Persons/index.tsx
Labels: feat, main

#57 [Park] person modal button 기능 추가 및 Big Menu 에 반영
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Persons/Person.tsx
  src/components/Persons/index.tsx
  src/contexts/PersonProvider.tsx
  tsconfig.json
Labels: feat, main

#65 refactor: 차트 관련 리팩토링
  .DS_Store
  src/components/Chart/Graph.tsx
  src/components/Chart/Title.tsx
  src/components/Chart/index.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/BigMenus.tsx
  src/contexts/PriceProvider.tsx
  tsconfig.path.json
Labels: bug, sub

#66 [Park] SearchResultPage layout + kakao map
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/common/util.ts
  src/components/Header/BigSearchBar/index.tsx
  src/components/Header/Logo.tsx
  src/components/Header/index.tsx
  src/components/Layout.tsx
  src/components/SearchResult/SkeletonRoom.tsx
  src/components/SearchResult/SkeletonRooms.tsx
  src/pages/MainPage.tsx
  src/pages/SearchResultPage.tsx
  src/types/global.d.ts
  webpack.config.js
Labels: feat, sub

#67 [Muffin] 검색결과 페이지 - 왼쪽 레이아웃 작업 ( 더미데이터 사용하여 화면 출력)
  public/room.json
  public/roomList.json
  src/assets/star_img.png
  src/assets/wish_img.png
  src/common/util.ts
  src/components/Header/BigSearchBar/SearchButton.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Main/NearByBox.tsx
  src/components/Main/SkeletonNearByBox.tsx
  src/components/SearchResult/Room.tsx
  src/components/SearchResult/Rooms.tsx
  src/pages/MainPage.tsx
  src/pages/SearchResultPage.tsx
Labels: feat, sub

#68 [Park] create mock server
  package-lock.json
  package.json
  public/mockServiceWorker.js
  public/room.json
  public/roomList.json
  src/components/Main/CategoryLocations.tsx
  src/components/Main/NearLocations.tsx
  src/components/Main/SkeletonNearLocations.tsx
  src/hooks/useFetch.tsx
  src/hooks/useThrottle.jsx
  src/index.tsx
  src/pages/MainPage.tsx
  src/pages/SearchResultPage.tsx
  src/server/browser.ts
  src/server/dummyData/categoryLocations.js
  src/server/dummyData/nearLocations.js
  src/server/dummyData/roomDetail.js
  src/server/dummyData/roomList.js
  src/server/handlers.ts
  tsconfig.json
  webpack.config.js
Labels: feat, sub

#70 feat: 검색 결과페이지 숙소 모달 관련 기능 작업, moment 라이브러리 추가
  package-lock.json
  package.json
  src/common/util.ts
  src/components/SearchResult/Room.tsx
  src/components/SearchResult/RoomModal.tsx
  src/components/SearchResult/Rooms.tsx
Labels: feat, sub

#76 [Muffin] modal창을 열었을때 Header 밀리는 현상
  src/components/SearchResult/RoomModal.tsx
Labels: bug

#75 [Muffin] 차트 슬라이드 에러 수정
  src/components/Chart/Graph.tsx
  src/components/Chart/index.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/contexts/PriceProvider.tsx
Labels: bug

#80 [Park] GitHub OAuth login
  src/App.tsx
  src/common/util.ts
  src/components/Header/UserInfo.tsx
  src/components/Loading.tsx
  src/components/OAuthCallback.tsx
  src/contexts/HeaderProvider.tsx
  src/index.tsx
  webpack.config.js
Labels: feat, main, sub
