Repository healtheloper/airbnb, pull requests merged in 2022-05, with the labels that each got.

#16 [Park] footer layout
  src/App.tsx
  src/common/theme.tsx
  src/components/Footer/Copyright.tsx
  src/components/Footer/FooterBottom.tsx
  src/components/Footer/FooterItems.tsx
  src/components/Footer/index.tsx
  src/mocks/footer.js
  tsconfig.json
  webpack.config.js
Labels: feat

#17 [Muffin] Header쪽 UI 수정 & Main Layout 작업
  src/App.tsx
  src/assets/hero-img.png
  src/common/theme.tsx
  src/components/FlexBox.tsx
  src/components/Header/Background.tsx
  src/components/Header/BigSearchBar.tsx
  src/components/Header/Category.tsx
  src/components/Header/MiniSearchBar.tsx
  src/components/Header/index.tsx
  src/constants/fontSize.ts
  src/pages/MainPage.tsx
  src/types/images.d.ts
  src/types/theme.d.ts
  tsconfig.json
  webpack.config.js
Labels: feat

#18 [Park] fix: webpack config 오타 수정
  webpack.config.js
Labels: bug

#41 [Park & Muffin] Refactor code review
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  src/components/Footer/FooterBottom.tsx
  src/components/Footer/FooterItems.tsx
  src/contexts/HeaderProvider.tsx
  src/hooks/useScroll.tsx
  src/mocks/footer.js
Labels: review

#43 [Park] header modal base 작성
  .eslintrc.js
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/BigMenus.tsx
  src/components/Header/BigSearchBar/Modal/index.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Header/MiniSearchBar/Menu.tsx
  src/components/Header/MiniSearchBar/Menus.tsx
  src/contexts/HeaderProvider.tsx
  webpack.config.js
Labels: feat, main

#44 [Muffin] 차트 기능 구현 진행 (레인지 슬라이더 적용 및 차트 샘플 작업)
  src/assets/room_sample.jpg
  src/components/Chart/index.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/mocks/room.js
Labels: feat
